const Icon = {
  // 首页
  homeIcon: require("../../assets/icon/home.svg"),
  // 列表
  listIcon: require("../../assets/icon/list.svg"),
  // 搜索
  searchIcon: require("../../assets/icon/search.svg"),
  // 碟片
  diskIcon: require("../../assets/icon/disk.svg"),
  // 笔记
  noteIcon: require("../../assets/icon/note.svg"),
  // 上一首
  lastIcon: require("../../assets/icon/last.svg"),
  // 下一首
  nextIcon: require("../../assets/icon/next.svg"),
  // 暂停
  pauseIcon: require("../../assets/icon/pause.svg"),
  // 播放
  playIcon: require("../../assets/icon/play.svg"),
  // 白色播放
  playWhiteIcon: require("../../assets/icon/play_white.svg"),
  // 上传
  uploadIcon: require("../../assets/icon/upload.svg"),
  // 添加
  addIcon: require("../../assets/icon/add.svg"),
  // 修改
  updateIcon: require("../../assets/icon/update.svg"),
  // 删除
  deleteIcon: require("../../assets/icon/delete.svg"),
  // 关闭
  closeIcon: require("../../assets/icon/close.svg"),
  // 声音
  soundOnIcon: require("../../assets/icon/sound_on.svg"),
  // 声音关闭
  soundOffIcon: require("../../assets/icon/sound_off.svg"),
  // 随机播放
  randomIcon: require("../../assets/icon/random.svg"),
  // 单曲循环
  singleIcon: require("../../assets/icon/single.svg"),
  // 列表播放
  loopIcon: require("../../assets/icon/loop.svg"),
  // 历史播放
  historyIcon: require("../../assets/icon/history.svg"),
  // 文件
  fileIcon: require("../../assets/icon/file.svg"),
  // 解析
  parseIcon: require("../../assets/icon/parse.svg"),
  // 评论
  commentIcon: require("../../assets/icon/comment.svg"),
  // 未收藏
  notLoveIcon: require("../../assets/icon/not_love.svg"),
  // 收藏-白色
  loveColorIcon: require("../../assets/icon/love_color.svg"),
  // 未点赞
  notLikeIcon: require("../../assets/icon/not_like.svg"),
  // 点赞
  likeIcon: require("../../assets/icon/like.svg"),
  // 头戴式耳机
  headsetIcon: require("../../assets/icon/headset.svg"),
  // 详情-白色
  detailWhiteIcon: require("../../assets/icon/detail_white.svg"),
  // 酷狗音乐
  kgyyIcon: require("../../assets/icon/kgyy.svg"),
  // QQ音乐
  qqyyIcon: require("../../assets/icon/qqyy.svg"),
  // 酷我音乐
  kwyyIcon: require("../../assets/icon/kwyy.svg"),
  // 网易云音乐
  wyyyyIcon: require("../../assets/icon/wyyyy.svg"),
  // 完成
  completeIcon: require("../../assets/icon/complete.svg"),
  // 日历
  calendarIcon: require("../../assets/icon/calendar.svg"),
  // 未登录头像
  notLoginIcon: require("../../assets/icon/not_login.svg"),
  // 数据管理
  dataManageIcon: require("../../assets/icon/data_manage.svg"),
  // 用户
  userIcon: require("../../assets/icon/user.svg"),
  // 建议
  suggestIcon: require("../../assets/icon/suggest.svg"),
  // 收藏夹
  collectIcon: require("../../assets/icon/collect.svg"),
  // 性别男
  maleIcon: require("../../assets/icon/male.svg"),
  // 性别女
  femaleIcon: require("../../assets/icon/female.svg"),
  // 未知性别
  unknowSexIcon: require("../../assets/icon/unknow_sex.svg"),
  // 下一页
  nextPageWhiteIcon: require("../../assets/icon/next_page_white.svg"),
  // 上一页
  lastPageWhiteIcon: require("../../assets/icon/last_page_white.svg"),
  // 音乐
  musicColorIcon: require("../../assets/icon/music.svg"),
  // 快进10秒
  forward10sIcon: require("../../assets/icon/forward10s.svg"),
  // 倒退10秒
  backward10sIcon: require("../../assets/icon/backward10s.svg"),
  // 人头
  peopleIcon: require("../../assets/icon/people.svg"),
  // mp3
  mp3Icon: require("../../assets/icon/mp3.svg"),
  // flac
  flacIcon: require("../../assets/icon/flac.svg"),
  // 密码
  passwordIcon: require("../../assets/icon/password.svg"),
  // 邮箱
  emailIcon: require("../../assets/icon/email.svg"),
  // 邀请码
  invitationIcon: require("../../assets/icon/invitation.svg"),
  // 微信
  wechatIcon: require("../../assets/icon/wechat.svg"),
  // 注册
  registerIcon: require("../../assets/icon/register.svg"),
  // deepseek
  deepseekIcon: require("../../assets/icon/deepseek.svg"),
  // deepseek带文字
  deepseekTIcon: require("../../assets/icon/deepseek_t.svg"),
  // 验证码
  verifyIcon: require("../../assets/icon/verify.svg"),
  // 唱片
  diskPng: require("../../assets/icon/disk.png"),
  // 唱针
  stylusPng: require("../../assets/icon/changzhen.png"),
}
export default Icon;