const Icon = {
    // 首页
    homeIcon: require("@/assets/home.svg"),
    // 列表
    listIcon: require("@/assets/list.svg"),
    // 搜索
    searchIcon: require("@/assets/search.svg"),
    // 碟片
    diskIcon: require("@/assets/disk.svg"),
    // 笔记
    noteIcon: require("@/assets/note.svg"),
    // 上一首
    lastIcon: require("@/assets/last.svg"),
    // 下一首
    nextIcon: require("@/assets/next.svg"),
    // 暂停
    pauseIcon: require("@/assets/pause.svg"),
    // 播放
    playIcon: require("@/assets/play.svg"),
    // 白色播放
    playWhiteIcon: require("@/assets/play_white.svg"),
    // 上传
    uploadIcon: require("@/assets/upload.svg"),
    // 添加
    addIcon: require("@/assets/add.svg"),
    // 修改
    updateIcon: require("@/assets/update.svg"),
    // 删除
    deleteIcon: require("@/assets/delete.svg"),
    // 关闭
    closeIcon: require("@/assets/close.svg"),
    // 声音
    soundOnIcon: require("@/assets/sound_on.svg"),
    // 声音关闭
    soundOffIcon: require("@/assets/sound_off.svg"),
    // 随机播放
    randomIcon: require("@/assets/random.svg"),
    // 单曲循环
    singleIcon: require("@/assets/single.svg"),
    // 列表播放
    loopIcon: require("@/assets/loop.svg"),
    // 历史播放
    historyIcon: require("@/assets/history.svg"),
    // 文件
    fileIcon: require("@/assets/file.svg"),
    // 解析
    parseIcon: require("@/assets/parse.svg"),
    // 评论
    commentIcon: require("@/assets/comment.svg"),
    // 未收藏
    notLoveIcon: require("@/assets/not_love.svg"),
    // 收藏-白色
    loveColorIcon: require("@/assets/love_color.svg"),
    // 未点赞
    notLikeIcon: require("@/assets/not_like.svg"),
    // 点赞
    likeIcon: require("@/assets/like.svg"),
    // 头戴式耳机
    headsetIcon: require("@/assets/headset.svg"),
    // 详情-白色
    detailWhiteIcon: require("@/assets/detail_white.svg"),
    // 酷狗音乐
    kgyyIcon: require("@/assets/kgyy.svg"),
    // QQ音乐
    qqyyIcon: require("@/assets/qqyy.svg"),
    // 酷我音乐
    kwyyIcon: require("@/assets/kwyy.svg"),
    // 网易云音乐
    wyyyyIcon: require("@/assets/wyyyy.svg"),
    // 完成
    completeIcon: require("@/assets/complete.svg"),
    // 日历
    calendarIcon: require("@/assets/calendar.svg"),
    // 未登录头像
    notLoginIcon: require("@/assets/not_login.svg"),
    // 数据管理
    dataManageIcon: require("@/assets/data_manage.svg"),
    // 用户
    userIcon: require("@/assets/user.svg"),
    // 建议
    suggestIcon: require("@/assets/suggest.svg"),
    // 收藏夹
    collectIcon: require("@/assets/collect.svg"),
    // 性别男
    maleIcon: require("@/assets/male.svg"),
    // 性别女
    femaleIcon: require("@/assets/female.svg"),
    // 未知性别
    unknowSexIcon: require("@/assets/unknow_sex.svg"),
    // 下一页
    nextPageWhiteIcon: require("@/assets/next_page_white.svg"),
    // 上一页
    lastPageWhiteIcon: require("@/assets/last_page_white.svg"),
    // 音乐
    musicColorIcon: require("@/assets/music.svg"),
    // 快进10秒
    forward10sIcon: require("@/assets/forward10s.svg"),
    // 倒退10秒
    backward10sIcon: require("@/assets/backward10s.svg"),
    // 人头
    peopleIcon: require("@/assets/people.svg"),
    // mp3
    mp3Icon: require("@/assets/mp3.svg"),
    // flac
    flacIcon: require("@/assets/flac.svg"),
    // 唱片
    diskPng: require("@/assets/disk.png"),
    // 唱针
    stylusPng: require("@/assets/changzhen.png"),

}
export default Icon;